name: CI

on:
  pull_request:

env:
  APP_DEV: ${{ secrets.APP_DEV }}
  PROJECT_HOST: ${{ secrets.PROJECT_HOST }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PWD: ${{ secrets.DB_PWD }}

jobs:
    tests:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: mariadb
          env:
            MYSQL_DATABASE: $DB_NAME
            MYSQL_ROOT_PASSWORD: $DB_PWD
          ports:
            - 3306:3306

      env:
        DATABASE_URL: mysql://root:$DB_ROOT_PWD@localhost:3306/$DB_NAME?serverVersion=10.5

      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP, extensions and composer with shivammathur/setup-php
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json, pdo, pgsql
            tools: composer:v2, phpunit:9.5, phpstan
          env:
            update: true

        # - name: Validate composer.json and composer.lock
        #   working-directory: ./AccountService
        #   run: |
        #     composer validate

        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v2
          with:
            working_dir: ./app
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-
        - name: Install dependencies
          working-directory: ./app
          run: |
            composer install --no-progress --prefer-dist --optimize-autoloader

        - name: Run phpunit for app
          working-directory: ./app
          env:
            DATABASE_URL: mysql://root:$DB_ROOT_PWD@localhost:3306/$DB_NAME?serverVersion=10.5
          run: vendor/bin/simple-phpunit

        - name: Run coding standards checks
          working-directory: ./app
          run: |
            vendor/bin/phpstan analyse
            vendor/bin/ecs check

